version: '3'
services:
  redis:
    image: redis:7-alpine
    container_name: quizapp_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: quizapp_postgres
    environment:
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: quizapp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@quizapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
